global using BoneLib;
global using BoneLib.Notifications;
global using HarmonyLib;
global using MelonLoader;
global using Object = UnityEngine.Object;
global using Paranoia.Helpers;
global using Paranoia.Managers;
global using PuppetMasta;
global using Random = UnityEngine.Random;
global using SLZ.AI;
global using SLZ.Bonelab;
global using SLZ.Marrow.Warehouse;
global using SLZ.Rig;
global using SLZ.SFX;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Linq;
global using UnhollowerBaseLib;
global using UnityEngine;
global using Utils = UnityEngine.Diagnostics.Utils;
global using UnityEngine.Diagnostics;
global using Paranoia.Internal;
global using BoneLib.BoneMenu;
global using Paranoia.Events;
global using Paranoia.Helpers;
global using Paranoia.Managers;
global using Paranoia.Entities;
global using SLZ.Props;
global using SLZ.Props.Weapons;